### ISSUE TITLE
ScummVM cannot start on upgrade to Fedora 29

### ISSUE THREAD

**Issue by ultraviolet-1986** [flathub/org.scummvm.ScummVM#3]
Hi, since upgrading to F29 on its final release yesterday, I cannot start ScummVM. When launching from the Terminal with `flatpak run org.scummvm.ScummVM`, I get the following:

`/app/bin/scummvm: symbol lookup error: /usr/lib/x86_64-linux-gnu/libreadline.so.7: undefined symbol: UP`

Not sure how to diagnose it, except that it looks like a library isn't pointing to the right place (sorry, I'm fairly new to Flatpak tech). Thank you very much for your time.

**Comment by AsciiWolf** [comment]
Thanks for reporting this! I am getting the same error on both Fedora 28 and Fedora 29. @TingPing Any idea?

**Comment by TingPing** [comment]
No idea, try rebuilding?

**Comment by AsciiWolf** [comment]
Hmm, build [failed](https://flathub.org/builds/#/builders/2/builds/5794) on all archs. It seems that the `libreadline.so` abi changed in some of the recent fd runtime updates and is not compatible with fluidsynth anymore.

**Comment by TingPing** [comment]
@AsciiWolf Can you test if any of these work:

```
History:
 Subject: Export org.freedesktop.Platform
 Date: 2018-10-22 22:35:06 +0000
 Commit: 63a47d7caa286021be5bc487d2b56585c447ea9bfc1df473eab61d2b9591afdf
 
 Subject: Export org.freedesktop.Platform
 Date: 2018-10-14 21:32:49 +0000
 Commit: e8df934455b4d92157787df8c02114cfb5ee6a231a7111bde44cf5974fa9f42d
 
 Subject: Export org.freedesktop.Platform
 Date: 2018-09-28 18:55:00 +0000
 Commit: 73e812f33b03b170bda57c577a2ff9f15f6fe88f6b16d43415311c72751d7693
 
 Subject: Export org.freedesktop.Platform
 Date: 2018-09-24 21:29:40 +0000
 Commit: 2eddd51a6035bc64f997083556d0570f45caebeac18676fe7dc6772a7c59f25e
```

`flatpak update --commit=$COMMIT org.freedesktop.Platform//18.08`
